Migrate from gulp
twilio/operation-retrier.ts pull request #4
Opened 2021-06-16 17:42 UTC by berkus

2021-06-16 18:01 UTC, InfiniteRain commented on rollup.config.js
> +const cdnSdkName = 'operation-retrier';
We probably don't need CDN versions of the bundle, as they're only ever consumed by our SDK's via NPM.

2021-06-16 18:01 UTC, InfiniteRain commented on rollup.config.js
> +  // Browser CDN bundle.
If previous comment is valid, then we shouldn't need the CDN bundle configs.

2021-06-16 18:01 UTC, InfiniteRain commented on package.json
> +    "ci": "yarn clean && yarn lint && yarn test:unit && yarn build && yarn sourceMapReport:html && yarn sourceMapReport:json && yarn docs"
Didn't we decide to get rid of `yarn test:unit` part?

2021-06-16 18:13 UTC, berkus commented on rollup.config.js
> +const cdnSdkName = 'operation-retrier';
kk

2021-06-16 18:33 UTC, berkus commented on package.json
> +    "ci": "yarn clean && yarn lint && yarn test:unit && yarn build && yarn sourceMapReport:html && yarn sourceMapReport:json && yarn docs"
Gone.

2021-06-16 18:33 UTC, berkus commented on rollup.config.js
> +  // Browser CDN bundle.
Will keep for the bright future.

2021-06-16 18:33 UTC, berkus commented on rollup.config.js
> +const cdnSdkName = 'operation-retrier';
Will keep for the bright future.

2021-06-17 14:04 UTC, InfiniteRain commented on rollup.config.js
> +      ignore: ['bufferutil', 'utf-8-validate'],
this part not needed as twilsock is not a dependency in here

2021-06-17 14:04 UTC, InfiniteRain commented on rollup.config.js
> +      ignore: ['bufferutil', 'utf-8-validate'],
this part not needed as twilsock is not a dependency in here

2021-06-17 14:04 UTC, InfiniteRain commented on rollup.config.js
> +      },
lets add `sourcemap: true` to here.

2021-06-17 14:04 UTC, InfiniteRain commented on rollup.config.js
> +const cdnSdkName = 'operation-retrier';
ok but let's rename the variable to `bundleName` as this lib is not an sdk

2021-06-21 13:07 UTC, InfiniteRain approved these changes
lgtm

2021-06-21 13:39 UTC, InfiniteRain requested changes

2021-06-21 13:39 UTC, InfiniteRain commented on rollup.config.js
> +// Name of the SDK, will be reflected in the file name of the CDN version.
change "SDK" to "bundle" in the comment

2021-06-21 14:24 UTC, InfiniteRain approved these changes

2021-06-21 14:24 UTC, merged